{{- if .Values.github.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.github.webhook.secretName }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: {{ .Values.github.webhook.secretName }}
    creationPolicy: Owner
  data:
    - secretKey: {{ .Values.github.webhook.secretKey }}
      remoteRef:
        key: homelab/data/secrets/github/webhook
        property: secret
{{- end }}
