apiVersion: v1
kind: Secret
metadata:
  name: argocd-vault-plugin-credential
type: Opaque
stringData:
  VAULT_ADDR: http://vault.vault:8200
  AVP_TYPE: vault
  AVP_AUTH_TYPE: k8s
  AVP_K8S_ROLE: argocd
