apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-tunnel-token
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: cloudflare-tunnel-token
    creationPolicy: Owner
  data:
    - secretKey: token
      remoteRef:
        key: homelab/data/secrets/cloudflare
        property: tunnel_token
