temporal:
  server:
    enabled: true
    config:
      persistence:
        defaultStore: default
        visibilityStore: visibility
        numHistoryShards: 512
        datastores:
          default:
            sql:
              createDatabase: true
              driverName: "postgres12"
              pluginName: "postgres12"
              host: temporal-postgresql-hl
              port: 5432
              database: temporal
              user: temporal
              existingSecret: temporal-postgresql
              secretKey: user-password
          visibility:
            sql:
              createDatabase: true
              driverName: "postgres12"
              pluginName: "postgres12"
              host: temporal-postgresql-hl
              port: 5432
              database: temporal_visibility
              user: temporal
              existingSecret: temporal-postgresql
              secretKey: user-password
  admintools:
    enabled: true
  web:
    enabled: true
    replicaCount: 1
postgresql:
  auth:
    enablePostgresUser: true
    username: temporal
    existingSecret: temporal-postgresql
    secretKeys:
      adminPasswordKey: postgres-password
      userPasswordKey: user-password
      replicationPasswordKey: replication-password
      metricsPasswordKey: metrics-password
  architecture: standalone
