temporal:
  server:
    enabled: true
    config:
      persistence:
        defaultStore: default
        default:
          driver: "sql"
          sql:
            driver: "postgres12"
            host: temporal-postgresql-hl
            port: 5432
            database: temporal
            user: postgres
            existingSecret: temporal-postgresql
            secretKey: user-password
        visibility:
          driver: "sql"
          sql:
            driver: "postgres12"
            host: temporal-postgresql-hl
            port: 5432
            database: temporal_visibility
            user: postgres
            existingSecret: temporal-postgresql
            secretKey: user-password
  admintools:
    enabled: true
  web:
    enabled: true
    replicaCount: 1
  elasticsearch:
    enabled: false
  prometheus:
    enabled: false
  grafana:
    enabled: false
  cassandra:
    enabled: false
postgresql:
  auth:
    enablePostgresUser: true
    existingSecret: temporal-postgresql
    secretKeys:
      adminPasswordKey: postgres-password
      userPasswordKey: user-password
      replicationPasswordKey: replication-password
      metricsPasswordKey: metrics-password
  architecture: standalone
