{
 "title": "Confluent Platform Community",
 "tags": [ "6.0.1" ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(cp_zookeeper_configversion, cluster)"
    }
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(cp_zookeeper_configversion, namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Confluent Kafka",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Brokers Online",
     "type": "stat",
     "description": "Number of Brokers Online",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(cp_kafka_server_replicamanager_leadercount{cluster=\"$cluster\", namespace=\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Active Controllers",
     "type": "stat",
     "description": "Number of active controllers in the cluster.",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(cp_kafka_controller_kafkacontroller_activecontrollercount{cluster=\"$cluster\", namespace=\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Unclean Leader Election Rate",
     "type": "stat",
     "description": "Unclean leader election rate",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(cp_kafka_controller_controllerstats_uncleanleaderelectionspersec{cluster=\"$cluster\", namespace=\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Online Partitions",
     "type": "stat",
     "description": "Partitions that are online",
     "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(cp_kafka_server_replicamanager_partitioncount{cluster=\"$cluster\", namespace=\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Under Replicated Partitions",
     "type": "stat",
     "description": "Number of under-replicated partitions (| ISR | < | all replicas |).",
     "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(cp_kafka_server_replicamanager_underreplicatedpartitions{cluster=\"$cluster\", namespace=\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Offline Partitions Count",
     "type": "stat",
     "description": "Number of partitions that don’t have an active leader and are hence not writable or readable.",
     "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(cp_kafka_controller_kafkacontroller_offlinepartitionscount{cluster=\"$cluster\", namespace=\"$namespace\"})"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "graph",
     "description": "Aggregated Kafka Broker Pods CPU Usage",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate (container_cpu_usage_seconds_total{pod=~\"$namespace-cp-kafka-(\\\\d+)\", namespace=~\"$namespace\"}[5m])) by (pod_name)",
       "legendFormat": "{{pod_name}}"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "graph",
     "description": "Kafka Broker Pods Memory Usage",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 5 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(container_memory_usage_bytes{pod=~\"$namespace-cp-kafka-(\\\\d+)\", namespace=~\"$namespace\", container!=\"\"}) by (pod)",
       "legendFormat": "{{pod_name}}"
      }
     ]
    },
    {
     "title": "Disk Usage",
     "type": "graph",
     "description": "Kafka Broker Pods Disk Usage",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 5 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "kubelet_volume_stats_used_bytes{persistentvolumeclaim=~\"datadir-0-$namespace-cp-kafka.*\"}",
       "legendFormat": "{{persistentvolumeclaim}}"
      }
     ]
    },
    {
     "title": "Byte Rate",
     "type": "graph",
     "description": "Byte Rate",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(cp_kafka_server_brokertopicmetrics_bytesinpersec{cluster=\"$cluster\", namespace=\"$namespace\"})",
       "legendFormat": "Incoming Byte Rate"
      },
      {
       "expr": "sum(cp_kafka_server_brokertopicmetrics_bytesoutpersec{cluster=\"$cluster\", namespace=\"$namespace\"})",
       "legendFormat": "Outgoing Byte Rate"
      }
     ]
    },
    {
     "title": "Messages In Per Second",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(cp_kafka_server_brokertopicmetrics_messagesinpersec{cluster=\"$cluster\", namespace=\"$namespace\"})",
       "legendFormat": "{{Messages In Per Second}}"
      }
     ]
    },
    {
     "title": "Produce Request Rate",
     "type": "graph",
     "description": "Produce Request Rate.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(cp_kafka_server_brokertopicmetrics_totalproducerequestspersec{cluster=\"$cluster\", namespace=\"$namespace\"})",
       "legendFormat": "Total Produce Request Rate"
      },
      {
       "expr": "sum(cp_kafka_server_brokertopicmetrics_failedproducerequestspersec{cluster=\"$cluster\", namespace=\"$namespace\"})",
       "legendFormat": "Failed Produce Request Rate"
      }
     ]
    },
    {
     "title": "Fetch Request Rate",
     "type": "graph",
     "description": "Fetch Request Rate",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(cp_kafka_server_brokertopicmetrics_totalfetchrequestspersec{cluster=\"$cluster\", namespace=\"$namespace\"})",
       "legendFormat": "Fetch Request Rate"
      },
      {
       "expr": "sum(cp_kafka_server_brokertopicmetrics_failedfetchrequestspersec{cluster=\"$cluster\", namespace=\"$namespace\"})",
       "legendFormat": "Failed Fetch Request Rate"
      }
     ]
    },
    {
     "title": "Network Processor Avg Idle Percent",
     "type": "graph",
     "description": "Network Processor Avg Idle Percent",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "cp_kafka_network_socketserver_networkprocessoravgidlepercent{cluster=\"$cluster\", namespace=\"$namespace\"}*100",
       "legendFormat": "{{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "Request Handler Avg Idle Percent",
     "type": "graph",
     "description": "Request Handler Avg Idle Percent",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "cp_kafka_kafkarequesthandlerpool_requesthandleravgidlepercent{cluster=\"$cluster\", namespace=\"$namespace\"}*100",
       "legendFormat": "{{kubernetes_pod_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Confluent Zookeeper",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Quorum Size",
     "type": "stat",
     "description": "Quorum Size of Zookeeper ensemble",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(cp_zookeeper_quorumsize{cluster=\"$cluster\", namespace=\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Alive Connections",
     "type": "stat",
     "description": "Number of Alive Connections",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(cp_zookeeper_numaliveconnections{cluster=\"$cluster\", namespace=\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Outstanding Requests",
     "type": "graph",
     "description": "Number of queued requests in the server. This goes up when the server receives more requests than it can process",
     "gridPos": { "h": 8, "w": 16, "x": 8, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "cp_zookeeper_outstandingrequests{cluster=\"$cluster\", namespace=\"$namespace\"}",
       "legendFormat": "{{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "Number of ZNodes",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(cp_zookeeper_inmemorydatatree_nodecount{cluster=\"$cluster\", namespace=\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Number of Watchers",
     "type": "stat",
     "description": "Number of Watchers",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(cp_zookeeper_inmemorydatatree_watchcount{cluster=\"$cluster\", namespace=\"$namespace\"})"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "graph",
     "description": "Aggregated Kafka Broker Pods CPU Usage",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"$namespace-cp-kafka-(\\\\d+)\", namespace=~\"$namespace\"}[5m])) by (pod)",
       "legendFormat": "{{pod_name}}"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "graph",
     "description": "Kafka Broker Pods Memory Usage",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 14 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(container_memory_usage_bytes{pod=~\"$namespace-cp-zookeeper-(\\\\d+)\", namespace=~\"$namespace\", container!=\"\"}) by (pod)",
       "legendFormat": "{{pod_name}}"
      }
     ]
    },
    {
     "title": "Disk Usage",
     "type": "graph",
     "description": "Kafka Broker Pods Disk Usage",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "kubelet_volume_stats_used_bytes{persistentvolumeclaim=~\"datadir-$namespace-cp-zookeeper.*\"}",
       "legendFormat": "{{persistentvolumeclaim}}"
      }
     ]
    },
    {
     "title": "Request Latency - Minimum",
     "type": "graph",
     "description": "Amount of time it takes for the server to respond to a client request",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "cp_zookeeper_minrequestlatency{cluster=\"$cluster\", namespace=\"$namespace\"}",
       "legendFormat": "{{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "Request Latency - Average",
     "type": "graph",
     "description": "Amount of time it takes for the server to respond to a client request",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "cp_zookeeper_avgrequestlatency{cluster=\"$cluster\", namespace=\"$namespace\"}",
       "legendFormat": "{{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "Request Latency - Maximum",
     "type": "graph",
     "description": "Amount of time it takes for the server to respond to a client request",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "cp_zookeeper_maxrequestlatency{cluster=\"$cluster\", namespace=\"$namespace\"}",
       "legendFormat": "{{kubernetes_pod_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Confluent Kafka Connect",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Number of Connectors",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "cp_kafka_connect_connect_worker_metrics_connector_count{cluster=\"$cluster\", namespace=\"$namespace\"}"
      }
     ]
    },
    {
     "title": "Connector Startup Success Total",
     "type": "stat",
     "description": "The total number of connector starts that succeeded.",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "cp_kafka_connect_connect_worker_metrics_connector_startup_success_total{cluster=\"$cluster\", namespace=\"$namespace\"}"
      }
     ]
    },
    {
     "title": "Connector Startup Failure Total",
     "type": "stat",
     "description": "The total number of connector starts that failed.",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "cp_kafka_connect_connect_worker_metrics_connector_startup_failure_total{cluster=\"$cluster\", namespace=\"$namespace\"}"
      }
     ]
    },
    {
     "title": "Number of Tasks",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 12, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "cp_kafka_connect_connect_worker_metrics_task_count{cluster=\"$cluster\", namespace=\"$namespace\"}"
      }
     ]
    },
    {
     "title": "Task Startup Success Total",
     "type": "stat",
     "description": "The total number of task starts that succeeded.",
     "gridPos": { "h": 4, "w": 4, "x": 16, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "cp_kafka_connect_connect_worker_metrics_task_startup_success_total{cluster=\"$cluster\", namespace=\"$namespace\"}"
      }
     ]
    },
    {
     "title": "Task Startup Failure Total",
     "type": "stat",
     "description": "The total number of task starts that failed.",
     "gridPos": { "h": 4, "w": 4, "x": 20, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "cp_kafka_connect_connect_worker_metrics_task_startup_failure_total{cluster=\"$cluster\", namespace=\"$namespace\"}"
      }
     ]
    },
    {
     "title": "Connect Metrics: IO Rate",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 41 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "cp_kafka_connect_connect_metrics_connect_1_io_ratio{cluster=\"$cluster\", namespace=\"$namespace\"}"
      }
     ]
    },
    {
     "title": "Connect Metrics: Incoming Byte Rate",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 41 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "cp_kafka_connect_connect_metrics_connect_1_incoming_byte_rate{cluster=\"$cluster\", namespace=\"$namespace\"}",
       "legendFormat": "{{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "Connect Metrics: Network IO Rate",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 41 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "cp_kafka_connect_connect_metrics_connect_1_network_io_rate{cluster=\"$cluster\", namespace=\"$namespace\"}",
       "legendFormat": "{{kubernetes_pod_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Confluent Kafka REST",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Number of Kafka REST servers",
     "type": "stat",
     "description": "Number of Kafka REST servers",
     "gridPos": { "h": 4, "w": 5, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(cp_kafka_rest_jetty_metrics_connections_active{cluster=\"$cluster\", namespace=\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Active Connections",
     "type": "stat",
     "description": "Total number of active TCP connections.",
     "gridPos": { "h": 4, "w": 5, "x": 5, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "cp_kafka_rest_jetty_metrics_connections_active{cluster=\"$cluster\", namespace=\"$namespace\"}"
      }
     ]
    },
    {
     "title": "Open Rate",
     "type": "stat",
     "description": "The average rate per second of opened TCP connections.",
     "gridPos": { "h": 4, "w": 5, "x": 10, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "cp_kafka_rest_jetty_metrics_connections_opened_rate{cluster=\"$cluster\", namespace=\"$namespace\"}"
      }
     ]
    },
    {
     "title": "Close Rate",
     "type": "stat",
     "description": "The average rate per second of closed TCP connections.",
     "gridPos": { "h": 4, "w": 5, "x": 15, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "cp_kafka_rest_jetty_metrics_connections_closed_rate{cluster=\"$cluster\", namespace=\"$namespace\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Confluent KSQL Server",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "KSQL Metrics: Bytes Consumed",
     "type": "graph",
     "description": "Total number of bytes consumed.",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "cp_ksql_server_metrics_bytes_consumed_total{cluster=\"$cluster\", namespace=\"$namespace\"}"
      }
     ]
    },
    {
     "title": "KSQL Metrics: Messages Consumed",
     "type": "graph",
     "description": "Messages consumed per second.",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "cp_ksql_server_metrics_messages_consumed_per_sec{cluster=\"$cluster\", namespace=\"$namespace\"}"
      }
     ]
    },
    {
     "title": "KSQL Metrics: Messages Produced",
     "type": "graph",
     "description": "Messages produced per second.",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "cp_ksql_server_metrics_messages_produced_per_sec{cluster=\"$cluster\", namespace=\"$namespace\"}"
      }
     ]
    },
    {
     "title": "KSQL Metrics: Active Queries",
     "type": "graph",
     "description": "Number of active queries.",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "cp_ksql_server_metrics_num_active_queries{cluster=\"$cluster\", namespace=\"$namespace\"}"
      }
     ]
    },
    {
     "title": "KSQL Metrics: Idle Queries",
     "type": "graph",
     "description": "Number of idle queries.",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "cp_ksql_server_metrics_num_idle_queries{cluster=\"$cluster\", namespace=\"$namespace\"}"
      }
     ]
    },
    {
     "title": "KSQL Metrics: Persistent Queries",
     "type": "graph",
     "description": "Number of persistent queries.",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "cp_ksql_server_metrics_num_persistent_queries{cluster=\"$cluster\", namespace=\"$namespace\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Confluent Schema Registry",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Number of Kafka Schema Registry servers",
     "type": "stat",
     "description": "Number of Kafka Schema Registry servers",
     "gridPos": { "h": 4, "w": 5, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(cp_kafka_schema_registry_jetty_metrics_connections_active{cluster=\"$cluster\", namespace=\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Active Connections",
     "type": "stat",
     "description": "Total number of active TCP connections.",
     "gridPos": { "h": 4, "w": 5, "x": 5, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "cp_kafka_schema_registry_jetty_metrics_connections_active{cluster=\"$cluster\", namespace=\"$namespace\"}"
      }
     ]
    },
    {
     "title": "Open Rate",
     "type": "stat",
     "description": "The average rate per second of opened TCP connections.",
     "gridPos": { "h": 4, "w": 5, "x": 10, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "cp_kafka_schema_registry_jetty_metrics_connections_opened_rate{cluster=\"$cluster\", namespace=\"$namespace\"}"
      }
     ]
    },
    {
     "title": "Close Rate",
     "type": "stat",
     "description": "The average rate per second of closed TCP connections.",
     "gridPos": { "h": 4, "w": 5, "x": 15, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "cp_kafka_schema_registry_jetty_metrics_connections_closed_rate{cluster=\"$cluster\", namespace=\"$namespace\"}"
      }
     ]
    }
   ]
  }
 ]
}