---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: temporal-postgresql
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: temporal-postgresql
    creationPolicy: Owner
  data:
    - secretKey: postgres-password
      remoteRef:
        key: homelab/data/secrets/temporal
        property: postgres_admin_password
    - secretKey: user-password
      remoteRef:
        key: homelab/data/secrets/temporal
        property: postgres_user_password
    - secretKey: replication-password
      remoteRef:
        key: homelab/data/secrets/temporal
        property: postgres_replication_password
    - secretKey: metrics-password
      remoteRef:
        key: homelab/data/secrets/temporal
        property: postgres_metrics_password
