nats:
  config:
    cluster:
      enabled: true
      replicas: 3
    jetstream:
      enabled: true
      fileStore:
        enabled: true
        dir: /data
        pvc:
          enabled: true
          size: 5Gi
          storageClassName:
  promExporter:
    enabled: true
    podMonitor:
      enabled: true
