apiVersion: tailscale.com/v1alpha1
kind: Connector
metadata:
  name: homelab-api
spec:
  replicas: 1
  hostnamePrefix: homelab-api-router
  subnetRouter:
    advertiseRoutes:
      - 192.168.1.100/32
      - 192.168.1.101/32
      - 192.168.1.102/32
      - 192.168.1.103/32
