cert-manager:
  crds:
    enabled: true
  prometheus:
    enabled: true
    servicemonitor:
      enabled: true
  serviceAccount:
    create: true
issuer:
  email: linhnguyen.workspace@gmail.com
x509-cert-exporter:
  prometheusServiceMonitor:
    create: true
  prometheusRules:
    create: true
