---
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: otel-collector
spec:
  mode: daemonset
  config: |
    receivers:
      zipkin:
      jaeger:
        protocols:
          grpc:
      otlp/http:
        protocols:
          http:
      otlp/grpc:
        protocols:
          grpc:
    processors:
      tail_sampling:
        decision_wait: 20s
        policies:
          - name: high-latency
            type: latency
            latency:
              threshold_ms: 500
          - name: error
            type: status_code
            status_code:
              status_codes:
                - ERROR
      batch:
    exporters:
      otlphttp:
        endpoint: http://tempo-distributor.tempo:4318
      loadbalancing:
        routing_key: "traceID"
        protocol:
          otlp:
            timeout: 1s
            tls:
              insecure: true
        resolver:
          k8s:
            service: otel-collector-collector.otel-collector

    service:
      pipelines:
        traces/loadbalancer:
          receivers: [otlp/http]
          processors: []
          exporters: [loadbalancing]
        traces/backend:
          receivers: [otlp/grpc]
          processors: [batch]
          exporters: [otlphttp]
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: otel-collector-collector
rules:
  - apiGroups: [""]
    resources: ["*"]
    verbs: ["get", "watch", "list"]
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["get", "watch", "list"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: otel-collector-collector
subjects:
  - kind: ServiceAccount
    name: otel-collector-collector
roleRef:
  kind: Role
  name: otel-collector-collector
  apiGroup: rbac.authorization.k8s.io
