apiVersion: batch/v1
kind: CronJob
metadata:
  name: renovate
spec:
  schedule: 0 * * * *
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: renovate
              image: renovate/renovate:latest
              env:
                - name: RENOVATE_PLATFORM
                  value: github
                - name: LOG_LEVEL
                  value: debug
                - name: RENOVATE_REPOSITORIES
                  value: linhng98/mess-around
                - name: RENOVATE_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: renovate-token
                      key: RENOVATE_TOKEN
          restartPolicy: Never
