apiVersion: v2
name: observability
version: 0.0.0
dependencies:
  - name: loki
    version: 17.4.4
    repository: https://grafana-community.github.io/helm-charts
  - name: promtail
    version: 6.17.1
    repository: https://grafana.github.io/helm-charts
  - name: kube-prometheus-stack
    version: 86.2.3
    repository: https://prometheus-community.github.io/helm-charts
    alias: prom
  - name: grafana
    version: 10.5.15
    repository: https://grafana.github.io/helm-charts
  - name: metrics-server
    version: 3.13.0
    repository: https://kubernetes-sigs.github.io/metrics-server
