loki:
  loki:
    commonConfig:
      replication_factor: 1
    schemaConfig:
      configs:
        - from: "2024-04-01"
          store: tsdb
          object_store: s3
          schema: v13
          index:
            prefix: loki_index_
            period: 24h
    ingester:
      chunk_encoding: snappy
    tracing:
      enabled: true
    querier:
      max_concurrent: 2
    storage:
      type: s3
      bucketNames:
        chunks: loki-bucket
        ruler: loki-bucket
      s3:
        endpoint: rook-ceph-rgw-ceph-objectstore.rook-ceph
        accessKeyId: ${AWS_ACCESS_KEY_ID}
        secretAccessKey: ${AWS_SECRET_ACCESS_KEY}
        s3ForcePathStyle: true
        insecure: true
  deploymentMode: Monolithic
  singleBinary:
    replicas: 1
    resources:
      limits:
        cpu: 3
        memory: 4Gi
      requests:
        cpu: 2
        memory: 2Gi
    extraEnv:
      - name: GOMEMLIMIT
        value: 3750MiB
    extraEnvFrom:
      - secretRef:
          name: loki-bucket
  chunksCache:
    writebackSizeLimit: 10MB
  minio:
    enabled: false
  backend:
    replicas: 0
  read:
    replicas: 0
  write:
    replicas: 0
  ingester:
    replicas: 0
  querier:
    replicas: 0
  queryFrontend:
    replicas: 0
  queryScheduler:
    replicas: 0
  distributor:
    replicas: 0
  compactor:
    replicas: 0
  indexGateway:
    replicas: 0
  bloomCompactor:
    replicas: 0
  bloomGateway:
    replicas: 0
promtail:
  config:
    logLevel: info
    serverPort: 3101
    clients:
      - url: http://{{ .Release.Name }}-loki-gateway/loki/api/v1/push
  serviceMonitor:
    enabled: true
metrics-server:
  metrics:
    enabled: true
  serviceMonitor:
    enabled: true
prom:
  grafana:
    enabled: false
  prometheusOperator:
    prometheusConfigReloader:
      resources:
        requests:
          cpu: 10m
          memory: 50Mi
  prometheus:
    prometheusSpec:
      ruleSelectorNilUsesHelmValues: false
      serviceMonitorSelectorNilUsesHelmValues: false
      podMonitorSelectorNilUsesHelmValues: false
      probeSelectorNilUsesHelmValues: false
      externalLabels:
        cluster: homelab
      retention: 15m # reduce retention to 15m due to https://grafana.com/docs/mimir/latest/operators-guide/mimir-runbooks/#err-mimir-sample-timestamp-too-old
      shards: 3
      #storageSpec:
      #  volumeClaimTemplate:
      #    spec:
      #      accessModes: [ReadWriteOnce]
      #      resources:
      #        requests:
      #          storage: 5Gi
      remoteWrite:
        - url: http://mimir-nginx.mimir/api/v1/push
          headers:
            X-Scope-OrgID: homelab
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/name
                    operator: In
                    values:
                      - prometheus
              topologyKey: kubernetes.io/hostname
  alertmanager:
    enabled: false
grafana:
  serviceMonitor:
    enabled: true
  deploymentStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  admin:
    existingSecret: grafana-admin-dashboard
    userKey: admin-user
    passwordKey: admin-password
  persistence:
    enabled: false
  plugins:
    - vonage-status-panel
    - grafana-piechart-panel
  sidecar:
    enableUniqueFilenames: false
    dashboards:
      enabled: true
      provider:
        # disableDelete to activate a import-only behaviour
        disableDelete: true
        # allow updating provisioned dashboards from the UI
        allowUiUpdates: false
        # allow Grafana to replicate dashboard structure from filesystem
        foldersFromFilesStructure: true
    datasources:
      enabled: true
      defaultDatasourceEnabled: false
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Loki
          type: loki
          uid: loki
          url: http://observability-loki-gateway
        - name: Tempo
          type: tempo
          uid: tempo
          url: http://tempo-gateway.tempo
          jsonData:
            serviceMap:
              httpMethod: GET
              datasourceUid: Prometheus
            search:
              hide: false
            nodeGraph:
              enabled: true
        - name: Prometheus
          isDefault: true
          type: prometheus
          uid: prometheus
          url: http://mimir-nginx.mimir/prometheus
          basicAuth: false
          jsonData:
            httpHeaderName1: X-Scope-OrgID
          secureJsonData:
            httpHeaderValue1: homelab
  grafana.ini:
    server:
      root_url: https://grafana.linhng98.com
    users:
      viewers_can_edit: true
    auth:
      disable_login_form: false
    #auth.google:
    #  enabled: true
    #  client_id: <path:homelab/data/google_oauth2/grafana#client_id>
    #  client_secret: <path:homelab/data/google_oauth2/grafana#client_secret>
    #  scopes: https://www.googleapis.com/auth/userinfo.profile https://www.googleapis.com/auth/userinfo.email
    #  auth_url: https://accounts.google.com/o/oauth2/auth
    #  token_url: https://accounts.google.com/o/oauth2/token
    #  allow_sign_up: true
    auth.anonymous:
      enabled: true
      org_role: Viewer
      hide_version: true
    feature_toggles:
      enable: tempoApmTable
