apiVersion: v2
name: rook-ceph-operator
version: 0.0.0
dependencies:
  - name: rook-ceph
    version: v1.20.2
    repository: https://charts.rook.io/release
  - name: ceph-csi-drivers
    version: 1.0.4
    repository: https://ceph.github.io/ceph-csi-operator
