apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-route53-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: "{{ .Values.issuer.email }}"
    privateKeySecretRef:
      name: letsencrypt-route53-prod
    solvers:
      - dns01:
          route53: {}
