apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-route53-prod
spec:
  acme:
    privateKeySecretRef:
      name: letsencrypt-route53-prod
    solvers:
      - dns01:
          route53: {}
