argo-events:
  crds:
    install: true
eventBus:
  enabled: true
  name: default
  replicas: 3
github:
  enabled: true
  owner: linhng98
  repositories:
    - mess-around
  webhook:
    host: argo-events.linhng98.com
    endpoint: /mess-around
    port: 12000
    url: https://argo-events.linhng98.com
    secretName: github-webhook
    secretKey: secret
  events:
    - "*"
  sensor:
    enabled: true
    triggerUrl: http://http-server.argo-events.svc:8090
    method: POST
httpServer:
  enabled: true
  name: http-server
  image:
    repository: mendhak/http-https-echo
    tag: "41"
    pullPolicy: IfNotPresent
  port: 8090
