apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tempo-bucket
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: rook-s3
  target:
    name: tempo-bucket
    creationPolicy: Owner
  data:
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: tempo-bucket
        property: AWS_ACCESS_KEY_ID
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: tempo-bucket
        property: AWS_SECRET_ACCESS_KEY
