name: pre-commit hook check
run-name: pre-commit hook check
on:
  pull_request:
jobs:
  pre-commit:
    runs-on: gha-selfhost
    steps:
      - uses: actions/checkout@v3
      - name: run pre-commit check
        run: |
          export PATH=$PATH:$HOME/.cargo/bin
          pre-commit run --show-diff-on-failure --color=always --all-files
